'use client';

import {
    Mountain, Landmark, Sun, Bike, Waves, Trees, Fish, Bird, MapPin,
    Sprout, Snowflake, Coffee, Camera, Flame
} from 'lucide-react';

export const EXPERIENCES = [
    {
        id: 'slowinski_dunes',
        icon: Mountain,
        labelKey: 'experiences.slowinski_dunes.title',
        descKey: 'experiences.slowinski_dunes.description',
        distanceMin: 65,
        duration: 'half-day',
        seasons: ['spring', 'summer', 'autumn'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['park-narodowy', 'wydmy', 'widoki', 'fotografia'],
    },
    {
        id: 'czolpino_lighthouse',
        icon: Landmark,
        labelKey: 'experiences.czolpino_lighthouse.title',
        descKey: 'experiences.czolpino_lighthouse.description',
        distanceMin: 60,
        duration: '1-2h',
        seasons: ['spring', 'summer', 'autumn'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['latarnia', 'widoki', 'bałtyk'],
    },
    {
        id: 'ustka_beach_promenade',
        icon: Sun,
        labelKey: 'experiences.ustka_beach_promenade.title',
        descKey: 'experiences.ustka_beach_promenade.description',
        distanceMin: 25,
        duration: '1-2h',
        seasons: ['all'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['plaża', 'molo', 'zachód-słońca', 'lody'],
    },
    {
        id: 'velo_baltica_segment',
        icon: Bike,
        labelKey: 'experiences.velo_baltica_segment.title',
        descKey: 'experiences.velo_baltica_segment.description',
        distanceMin: 15,
        duration: 'half-day',
        seasons: ['spring', 'summer', 'autumn'],
        suitableFor: ['teens', 'adults', 'seniors'],
        tags: ['rowery', 'trasa-r10', 'wybrzeże'],
    },
    {
        id: 'kayak_slupia',
        icon: Waves,
        labelKey: 'experiences.kayak_slupia.title',
        descKey: 'experiences.kayak_slupia.description',
        distanceMin: 15,
        duration: 'half-day',
        seasons: ['spring', 'summer', 'autumn'],
        suitableFor: ['teens', 'adults'],
        tags: ['kajaki', 'rzeka', 'przygoda'],
    },
    {
        id: 'gardno_sup_windsurf',
        icon: Waves,
        labelKey: 'experiences.gardno_sup_windsurf.title',
        descKey: 'experiences.gardno_sup_windsurf.description',
        distanceMin: 45,
        duration: 'half-day',
        seasons: ['spring', 'summer'],
        suitableFor: ['teens', 'adults'],
        tags: ['sup', 'windsurf', 'jezioro', 'slpn'],
    },
    {
        id: 'rowy_family_beach',
        icon: Sun,
        labelKey: 'experiences.rowy_family_beach.title',
        descKey: 'experiences.rowy_family_beach.description',
        distanceMin: 35,
        duration: '1-2h',
        seasons: ['summer'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['plaża', 'rodziny', 'lody', 'spacery'],
    },
    {
        id: 'kluki_skansen',
        icon: Landmark,
        labelKey: 'experiences.kluki_skansen.title',
        descKey: 'experiences.kluki_skansen.description',
        distanceMin: 45,
        duration: '1-2h',
        seasons: ['spring', 'summer', 'autumn'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['muzeum', 'kultura', 'historia', 'słowińcy'],
    },
    {
        id: 'swolowo_kraina_w_krate',
        icon: Landmark,
        labelKey: 'experiences.swolowo_kraina_w_krate.title',
        descKey: 'experiences.swolowo_kraina_w_krate.description',
        distanceMin: 20,
        duration: '1-2h',
        seasons: ['all'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['skansen', 'zagroda', 'regionalne-smaki'],
    },
    {
        id: 'dolina_charlotty_zoo_spa',
        icon: Landmark,
        labelKey: 'experiences.dolina_charlotty_zoo_spa.title',
        descKey: 'experiences.dolina_charlotty_zoo_spa.description',
        distanceMin: 15,
        duration: 'half-day',
        seasons: ['all'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['spa', 'zoo', 'koncerty', 'wakepark'],
    },
    {
        id: 'birdwatching_gardno_lebsko',
        icon: Bird,
        labelKey: 'experiences.birdwatching_gardno_lebsko.title',
        descKey: 'experiences.birdwatching_gardno_lebsko.description',
        distanceMin: 50,
        duration: '1-2h',
        seasons: ['spring', 'autumn'],
        suitableFor: ['teens', 'adults', 'seniors'],
        tags: ['ptaki', 'ornitologia', 'platformy-widokowe'],
    },
    {
        id: 'foraging_mushrooms_herbs',
        icon: Sprout,
        labelKey: 'experiences.foraging_mushrooms_herbs.title',
        descKey: 'experiences.foraging_mushrooms_herbs.description',
        distanceMin: 0,
        duration: '1-2h',
        seasons: ['summer', 'autumn'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors', 'pets'],
        tags: ['grzybobranie', 'zioła', 'las'],
    },
    {
        id: 'horse_riding',
        icon: Trees,
        labelKey: 'experiences.horse_riding.title',
        descKey: 'experiences.horse_riding.description',
        distanceMin: 25,
        duration: '1-2h',
        seasons: ['spring', 'summer', 'autumn', 'winter'],
        suitableFor: ['kids', 'teens', 'adults'],
        tags: ['konie', 'hipoterapia', 'rajdy'],
    },
    {
        id: 'bonfire_bbq_garden',
        icon: Flame,
        labelKey: 'experiences.bonfire_bbq_garden.title',
        descKey: 'experiences.bonfire_bbq_garden.description',
        distanceMin: 0,
        duration: '1-2h',
        seasons: ['spring', 'summer', 'autumn'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors', 'pets'],
        tags: ['ognisko', 'grill', 'wieczór'],
    },
    {
        id: 'fishing_baltic_or_lakes',
        icon: Fish,
        labelKey: 'experiences.fishing_baltic_or_lakes.title',
        descKey: 'experiences.fishing_baltic_or_lakes.description',
        distanceMin: 30,
        duration: 'half-day',
        seasons: ['spring', 'summer', 'autumn', 'winter'],
        suitableFor: ['teens', 'adults', 'seniors'],
        tags: ['wędkarstwo', 'rejsy', 'jeziora', 'bałtyk'],
    },
    {
        id: 'sarbsk_sea_park',
        icon: Landmark,
        labelKey: 'experiences.sarbsk_sea_park.title',
        descKey: 'experiences.sarbsk_sea_park.description',
        distanceMin: 60,
        duration: 'half-day',
        seasons: ['spring', 'summer', 'autumn'],
        suitableFor: ['kids', 'teens', 'adults'],
        tags: ['foki', 'park-rodzinny', 'pokazy'],
    },
    {
        id: 'leba_dinopark',
        icon: Camera,
        labelKey: 'experiences.leba_dinopark.title',
        descKey: 'experiences.leba_dinopark.description',
        distanceMin: 70,
        duration: '1-2h',
        seasons: ['spring', 'summer', 'autumn'],
        suitableFor: ['kids', 'teens'],
        tags: ['park-tematyczny', 'dzieci'],
    },
    {
        id: 'redzikowo_aquapark',
        icon: Waves,
        labelKey: 'experiences.redzikowo_aquapark.title',
        descKey: 'experiences.redzikowo_aquapark.description',
        distanceMin: 10,
        duration: '1-2h',
        seasons: ['all'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['basen', 'zjeżdżalnie', 'sauny'],
    },
    {
        id: 'mps_slab_city_museum_witkacy',
        icon: Landmark,
        labelKey: 'experiences.mps_slab_city_museum_witkacy.title',
        descKey: 'experiences.mps_slab_city_museum_witkacy.description',
        distanceMin: 10,
        duration: '1-2h',
        seasons: ['all'],
        suitableFor: ['teens', 'adults', 'seniors'],
        tags: ['muzeum', 'sztuka', 'witkacy'],
    },
    {
        id: 'darlowo_castle_lighthouse',
        icon: Landmark,
        labelKey: 'experiences.darlowo_castle_lighthouse.title',
        descKey: 'experiences.darlowo_castle_lighthouse.description',
        distanceMin: 70,
        duration: 'half-day',
        seasons: ['all'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['zamek', 'latarnia', 'morze'],
    },
    {
        id: 'kolobrzeg_old_town_pier',
        icon: MapPin,
        labelKey: 'experiences.kolobrzeg_old_town_pier.title',
        descKey: 'experiences.kolobrzeg_old_town_pier.description',
        distanceMin: 90,
        duration: 'half-day',
        seasons: ['all'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['molo', 'stare-miasto', 'spa'],
    },
    {
        id: 'sauna_spa_relax',
        icon: Landmark,
        labelKey: 'experiences.sauna_spa_relax.title',
        descKey: 'experiences.sauna_spa_relax.description',
        distanceMin: 15,
        duration: '1-2h',
        seasons: ['autumn', 'winter', 'spring'],
        suitableFor: ['adults', 'seniors'],
        tags: ['sauna', 'wellness', 'relaks'],
    },
    {
        id: 'winter_forest_walks',
        icon: Snowflake,
        labelKey: 'experiences.winter_forest_walks.title',
        descKey: 'experiences.winter_forest_walks.description',
        distanceMin: 0,
        duration: '1-2h',
        seasons: ['winter'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors', 'pets'],
        tags: ['spacer', 'las', 'cisza'],
    },
    {
        id: 'local_cafes_bakeries',
        icon: Coffee,
        labelKey: 'experiences.local_cafes_bakeries.title',
        descKey: 'experiences.local_cafes_bakeries.description',
        distanceMin: 10,
        duration: '1-2h',
        seasons: ['all'],
        suitableFor: ['kids', 'teens', 'adults', 'seniors'],
        tags: ['kawiarnie', 'śniadania', 'lokalne-smaki'],
    },
];


export const EXPERIENCE_GROUPS = [
    {
        id: 'nature',
        titleKey: 'experiences.groups.nature',
        items: [
            'slowinski_dunes',
            'czolpino_lighthouse',
            'rowy_family_beach',
            'birdwatching_gardno_lebsko',
            'winter_forest_walks',
        ],
    },
    {
        id: 'water',
        titleKey: 'experiences.groups.water',
        items: [
            'ustka_beach_promenade',
            'gardno_sup_windsurf',
            'kayak_slupia',
            'redzikowo_aquapark',
            'fishing_baltic_or_lakes',
            'kolobrzeg_old_town_pier',
        ],
    },
    {
        id: 'active',
        titleKey: 'experiences.groups.active',
        items: [
            'velo_baltica_segment',
            'horse_riding',
            'bonfire_bbq_garden',
        ],
    },
    {
        id: 'culture',
        titleKey: 'experiences.groups.culture',
        items: [
            'kluki_skansen',
            'swolowo_kraina_w_krate',
            'mps_slab_city_museum_witkacy',
            'darlowo_castle_lighthouse',
        ],
    },
    {
        id: 'family',
        titleKey: 'experiences.groups.family',
        items: [
            'sarbsk_sea_park',
            'leba_dinopark',
            'rowy_family_beach',
            'ustka_beach_promenade',
        ],
    },
    {
        id: 'food_relax',
        titleKey: 'experiences.groups.food_relax',
        items: [
            'local_cafes_bakeries',
            'sauna_spa_relax',
            'swolowo_kraina_w_krate',
            'bonfire_bbq_garden',
        ],
    },
];
